### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by KingBBQ** [Francesco-Sch/prompt-slam#22]
Just trying your code, I get this error:

`Error: Request failed with status code 400
    at createError (/Users/kingbbq/src/prompt-battle/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/kingbbq/src/prompt-battle/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/kingbbq/src/prompt-battle/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1376:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'OpenAI/NodeJS/3.3.0',`

API-Key is set, credits for DALL-E are there...
It seems to run otherwise, just the image creation seems wrong.

**Comment by Francesco-Sch** [comment]
Hey @KingBBQ ,

when does this error exactly appear? After sending the prompt?

**Comment by KingBBQ** [comment]
yes, right after sending the prompt. I click "Generate the image", get an errer in the browser (An error occurred, please try again.).

**Comment by Francesco-Sch** [comment]
Hi @KingBBQ,

this was propably because OpenAI updated their API and I needed to adjust the API call. 
Now everything works as intended. Could you check again?

**Comment by Francesco-Sch** [comment]
Hi @KingBBQ,

this was propably because OpenAI updated their API and I needed to adjust the API call. 
Now everything works as intended. Could you check again?

**Comment by Francesco-Sch** [comment]
This issue is closed due to inactivity.
